name: Lint Project

on:
    push:
        branches:
            - main
            - dev/knex/pgsql

jobs:
    lint:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./
        steps:
            - name: Check Project
              uses: actions/setup-node@v3
              with:
                  node-version: "16"
                  script: |
                      cd ..
                      yarn lint
