name: Test Build

on:
  pull_request:
    branches: 
      - next
      
    paths:
      - "./**/*.ts"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test if build is successful
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - run: npm run deps:get
    - run: yarn build